### ISSUE TITLE
Plotting service export feature broken

### ISSUE THREAD

**Issue by NewBermuda** [HdrHistogram/HdrHistogram#166]
Dear HdrHistogram team,

I'm currently trying to use your latency percentile distribution percentile feature from your website (http://hdrhistogram.github.io/HdrHistogram/plotFiles.html).
However, the export image feature from the website seems to be broken.
Neither Chrome or Firefox seem to work.
Could you try to fix it? 
When looking at developer tools of firefox, 
it seems to throw a security error:
`SecurityError: CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet`

Kind regards

**Comment by giltene** [comment]
Fixed with https://github.com/HdrHistogram/HdrHistogram/commit/45e61818513fc69b1112aac58ab94dfcd240f080. I think. Please check on your end to verify and comment here before I close.

**Comment by NewBermuda** [comment]
Thank you for the quick response.
Unfortunately, it's still not working.
Now it throws a 'typeerror: el is null' at plotfiles.html:287:29
> 
> 
> Fixed with [45e6181](https://github.com/HdrHistogram/HdrHistogram/commit/45e61818513fc69b1112aac58ab94dfcd240f080). I think. Please check on your end to verify and comment here before I close.

**Comment by giltene** [comment]
Can you elaborate of the platform, browser, and data you are using? I just tested it on a Mac with Safari, Firefox, and Chrome, and with a .hgrm file being loaded, and on an iPad with Safari, and they all seem to support right-clicking on the image to save it, open it in a separate tab.

**Comment by NewBermuda** [comment]
Thanks, I now understood that you're supposed to simply use right-click and save it. Works now!

**Comment by giltene** [comment]
Great! Thanks for pointing this out. It was a quick and easy fix and a very useful improvement to the plotting page
